In [1]:
# import
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [9]:
#  Changes the shape of a tensor without altering its size or values
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X_my = x.reshape(4, 3)
X_my

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

# 🧩 Key Idea: Using -1 in reshape

When reshaping, you don’t need to specify every dimension manually. Why? Because PyTorch can figure out the missing one automatically using: total elements ÷ product of other dimensions. You tell PyTorch: “Figure this one out for me.” By writing -1.

### Suppose you have a tensor x with 12 elements.

x = torch.arange(12) # [0,1,2,...,11]

You want to reshape it to (3, 4):

- Normal way: \*
  x.reshape(3, 4)

- But this is equivalent:\*
  x.reshape(-1, 4)

Here:

PyTorch sees you want: some rows = ? columns = 4
total elements = 12
so number of rows = 12 / 4 = 3 _Automatically inferred._
So it becomes (3, 4).

Another equivalent:
x.reshape(3, -1)

This time:
rows = 3
columns = ?

So:
columns = 12 / 3 = 4
It becomes (3, 4) again.

### ✔️ Rule

You can use exactly one -1 in reshape.
Because only one dimension can be inferred.

### ✨ WHY THIS IS USEFUL

When coding, you often don't know one dimension easily.

Example:
You know each sample has 784 pixels (MNIST), but batch size varies.

So you can write:

x.reshape(-1, 784)

PyTorch will set the batch size automatically.

This makes code cleaner, safer, and dynamic.

### 🧪 Bonus: Examples with real shapes

Say we have a tensor of shape (2, 3, 4)
Total elements: 2 _ 3 _ 4 = 24

We can reshape to:
x.reshape(4, 6)
x.reshape(6, 4)
x.reshape(8, 3)
x.reshape(3, 8)
x.reshape(-1, 6) # => (4, 6)
x.reshape(2, -1) # => (2, 12)


In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

the parameters of neural networks are often initialized randomly. The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.


In [12]:
torch.randn(3, 4)

tensor([[-0.4364,  0.7483, -0.2190,  0.1149],
        [ 0.0931,  0.7657,  0.0834,  1.7440],
        [ 1.0460,  1.2721, -0.9176, -1.5665]])

In [13]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

X[start:stop], where the returned value includes the first index (start) but not the last (stop). Finally, when only one index (or slice) is specified for a
-order tensor, it is applied along axis 0. Thus, in the following code, [-1] selects the last row and [1:3] selects the second and third rows.


In [14]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
# Beyond reading them, we can also write elements of a matrix by specifying indices
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

# NumPy Slicing (Complete Explanation in One Cell)

NumPy slicing lets you extract or modify parts of an array. The general form is:

`array[start:stop:step]`

- `start`: index to begin (inclusive), default = 0
- `stop`: index to end (exclusive), default = end of array
- `step`: how much to skip, default = 1

Examples:

- `x[:]` → all elements
- `x[1:4]` → elements at indices 1,2,3
- `x[::2]` → every second element
- `x[::-1]` → reversed array

---

## Multi-Dimensional Slicing

For 2D arrays, each dimension has its own slice:

`X[row_slice, col_slice]`

Examples:

- `X[:, :]` → all rows, all columns
- `X[1, :]` → row 1, all columns
- `X[:, 2]` → column 2, all rows
- `X[1:3, 0:2]` → rows 1–2, cols 0–1

---

## Using `:` in Different Ways

### 1. Select first N rows:

`X[:2, :]`

- rows 0 and 1
- all columns

### 2. Select first M columns:

`X[:, :3]`

- all rows
- columns 0,1,2

### 3. Select with step:

`X[::2, :]`

- every second row

### 4. Reverse rows/columns:

- rows reversed: `X[::-1, :]`
- columns reversed: `X[:, ::-1]`

---

## Negative Indices

Negative numbers count from the end:

- `X[-1, :]` → last row
- `X[:, -2:]` → last two columns
- `X[:-1, :]` → all rows except last

---

## Assignment and Broadcasting

You can assign values to slices:

`X[:2, :] = 11`

- selects first two rows
- fills all elements with `11`

NumPy broadcasts scalars to fit the slice automatically.

---

## Views vs Copies (Important)

Slicing usually returns a **view**, not a copy.  
Modifying a slice changes the original array.

```python
s = X[:2, :]
s[:] = 99   # modifies X too
```


In [17]:
X[:2, :] = 11
X

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [ 8.,  9., 10., 11.]])